### PR TITLE
Mention about distribution-spec

### PR DESCRIPTION
**Pull request by fazlan-nazeem**
fixes https://github.com/opencontainers/opencontainers.org/issues/117

### CODE REVIEW

**Comment by fazlan-nazeem** [comment]
@celestehorgan @caniszczyk please review

**Review by sudo-bmitch — COMMENTED** [review]
These changes LGTM. I'm also seeing the faq.md on line 119:

> ## Will OCI ever add additional specifications– such as networking, inter-container communication, or distribution– to its scope?
> 
> The OCI has purposefully been limited in scope, see the OCI Scope Table for more information. In the future, the scope may slightly expand to discuss items such as distribution, but there is nothing formally planned at the moment.

**Comment by fazlan-nazeem** [comment]
> These changes LGTM. I'm also seeing the faq.md on line 119:
> 
> > ## Will OCI ever add additional specifications– such as networking, inter-container communication, or distribution– to its scope?
> > The OCI has purposefully been limited in scope, see the OCI Scope Table for more information. In the future, the scope may slightly expand to discuss items such as distribution, but there is nothing formally planned at the moment.

Thank you for noticing this. I have now done a modification to the content on that section. Let me know if it looks fine or if further changes are needed.

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Comment by fazlan-nazeem** [comment]
Anything more we need before merging this? If not, can someone merge this, please?

**Review by samuelkarp — APPROVED** [review]

**Pull request merged**
