### PR TITLE
Update members.html

### PR DESCRIPTION
**Pull request by amye**

### CODE REVIEW

**Comment by sudo-bmitch** [comment]
Did these all drop at once, or is it catching up on several years of changes?

**Comment by amye** [comment]
The 2nd, this is multiple years that I had on my list to clean up for 2024.

**Review by sudo-bmitch — APPROVED** [review]
Oh boy, that's a lot of red, but the page render LGTM.

**Review by samuelkarp — APPROVED** [review]

**Comment by caniszczyk** [comment]
Thanks merged! We also will have a draft OCI in 2024 blog post here for review https://github.com/opencontainers/opencontainers.org/pull/140

**Pull request merged**
