### PR TITLE
Create 2021-01-29-oci-in-2021.md

### PR DESCRIPTION
**Pull request by caniszczyk**
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
preview here: https://deploy-preview-75--opencontainers.netlify.app/posts/blog/2021-01-29-oci-in-2021/

**Review by estesp — APPROVED** [review]
LGTM!

**Comment by vbatts** [comment]
LGTM

**Review by samuelkarp — APPROVED** [review]
LGTM

**Review by fuweid — APPROVED** [review]
LGTM

**Pull request merged**
