### PR TITLE
update copyright year in footer

### PR DESCRIPTION
**Pull request by salaxander**
Noticed the copyright year in the site footer was a bit out of date, so I've got a quick PR to correct it.

### CODE REVIEW

**Comment by caniszczyk** [comment]
@salaxander can you update with DCO ?

**Comment by jonjohnsonjr** [comment]
The copyright year asserts the first year of publication of a work. It is not necessary to update the year, and doing so actually weakens the copyright assertion unless you use a range of years that starts with the earliest year.

**Comment by caniszczyk** [comment]
honestly we should probably drop the year tbh, not really a best practice anymore across LF projects, e.g., https://github.com/cncf/foundation/blob/main/copyright-notices.md#copyright-notices

**Comment by salaxander** [comment]
@caniszczyk - I can alter this PR to remove the year from the footer all together if that's preferred?

**Comment by salaxander** [comment]
Removed the year altogether

**Pull request merged**
