### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by amye**
Editing typo in title
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>

### CODE REVIEW

**Review by samuelkarp — APPROVED** [review]

**Comment by samuelkarp** [comment]
@amye It looks like the commit message is still missing the `Signed-off-by` line so it's failing the DCO check.  You can fix this with `git commit -s --amend` and then force-pushing to your existing branch.

**Comment by amye** [comment]
Curses, the new commit did have Signed-off-by: Amye Scavarda Perrin amye@linuxfoundation.org

**Review by samuelkarp — APPROVED** [review]

**Comment by mikebrow** [comment]
Amye can you squash your commits.. the last one is signed but not the first few.

**Comment by jdolitsky** [comment]
@amye - do you want to close/re-open this PR?

**Pull request closed without merging**
